### ISSUE TITLE
Wrong boot order

### ISSUE THREAD

**Issue by WNC12k** [Forevener/DRPGSEL#6]
The latest version of the Launcher has a bug, namely:

After starting the game, quit and restarting [DRPGSEL](https://github.com/Forevener/DRPGSEL), the folder with DoomRPG becomes the second in the boot order. And need have to manually correct the order.

Just want to point out, although I'm sure you know this without me: DoomRPG should always be loaded last, then you have to load the patches (I hope this works correctly in the launcher, since the order of the patches is not visible).

Can you fix this?

![1](https://user-images.githubusercontent.com/40601544/187749797-cc7bd49b-d2ea-45bf-accf-a9e407a00679.PNG)

EDIT: After clicking Reload - the folder with DoomRPG completely disappeared from the list. This is in addition to the previous algorithm.

![2](https://user-images.githubusercontent.com/40601544/187754674-d90d0509-403b-468a-ad16-fcd5a35ae886.PNG)

A wish for the future (if there is time):
And it wouldn't be bad to see and control the order of loading compatibility patches, at some point it might be necessary.

**Comment by Forevener** [comment]
Please take a look at the latest version.
Manual patch control is back - at first I've made it automatic to prevent user errors related to wrong load order.
Also note: the launcher supports directories inside the "Mods" folder, so you could sort all your mods by categories if you would like to.

**Comment by WNC12k** [comment]
![Uploading 1.PNG…]()

**Comment by WNC12k** [comment]
![1](https://user-images.githubusercontent.com/40601544/188278739-1d89ddd7-1aed-4e5c-937c-511a5f58c2da.PNG)

**Comment by WNC12k** [comment]
It's like it doesn't work. I keep trying.

**Comment by WNC12k** [comment]
And I threw in a Launcher concept, if you'll excuse me
![1](https://user-images.githubusercontent.com/40601544/188278990-e1e8caf4-b423-4837-b9df-dde87a2b3d6b.PNG)

**Comment by Forevener** [comment]
Heh, the check was implemented unwisely... It is fixed now, please redownload.
But why would you like to have separate control for patches load order? They are basically mods in their own way, and it would be more flexible to change their order among all mods.

**Comment by WNC12k** [comment]
![1](https://user-images.githubusercontent.com/40601544/188284738-7c728739-7e1d-41bd-9b78-377a4261bd37.PNG)

I started testing the definition of the required patches, then pressed the Reload button several times, and got this. 

And also the boot order was changed, before pressing the Reload button. 

Can you work on this some more?

**Comment by WNC12k** [comment]
> Heh, the check was implemented unwisely... It is fixed now, please redownload. But why would you like to have separate control for patches load order? They are basically mods in their own way, and it would be more flexible to change their order among all mods.

No problem, it just seems more logical from my point of view. Just sharing an idea :)

**Comment by Forevener** [comment]
Should be fixed now, please give it a try.

**Comment by WNC12k** [comment]
Now it works! Thank you! But I have two more comments. 

**1)** Here is the identical situation in two different versions of the Launcher:
![1](https://user-images.githubusercontent.com/40601544/188301511-92ae49c3-df0a-4377-9c35-2503be8d5c25.PNG)

LegenDoom_2.8.3 in Launcher 1.03 required only 1 major patch.

In Launcher 1.3.0 version, LegenDoom_2.8.3 requires both a basic and an optional patch (designed to work with monsterpacks).

Is this a bug or is it designed that way? Note that this patch does not appear in COMPATINFO:
![2](https://user-images.githubusercontent.com/40601544/188301642-72303b28-e22f-4dfb-9a65-4f68fb545946.PNG)

However, in DRPGINFO there is a link to the file LegenDoom_2.8.3:
![3](https://user-images.githubusercontent.com/40601544/188301656-dfc92b57-04a9-4ff6-a214-38f987aa0c93.PNG)

Is this the way it's designed and I now need to remove the binding from DRPGINFO in the Mods line? Or is that a bug?

**2)** In DRLA Extended, there were additional classes. Can they be included in the Launcher selection?

**Comment by Forevener** [comment]
You are welcome! Thank you for the meticulous testing.
1) I decided to drop the COMPATINFO altogether, since we have more precise control over versions, requirements and conflicts in DRPGINFO. So it has to be updated accordingly. Please note that DRPGINFO now supports keyword 'requires' for required patches (for example 'Requires=LegenDoom').
The message you are seeing is from the function designed to scan active mods and find if DoomRPG has patches for them. It doesn't really consider the optional nature of them, so let's think how could we solve that. First suggestion - remove the requirement for the mod in optional patch, and instead add the requirement for the base patch.

2) If it has to be done - it will be done. Should be simple enough...

**Comment by WNC12k** [comment]
1. I tried "Requires=LegenDoom". It seems to work as it should. Thank you!
2. Yes it is necessary. Please do.

**Comment by Forevener** [comment]
1. Great!
2. Did it yesterday, but I'm preparing to include one more addition for the next release, so here we go:
3. What are latest rules for DoomRPG+patches load order? I want to make compatibility check function more gentle, because getting errors during every wrong move could be frustrating, and I would like to include current recommendations into launcher's suggestions. Is it always "Last place"?

**Comment by WNC12k** [comment]
Example load order from https://github.com/WNC12k/DoomRPG-Rebalance#manual-installing:

1. WadSmoosh and/or The Sentinel's Lexicon - PvE mapset Compilaition or another mapset;
2. DoomRL Arsenal 1.1.5 or LegenDoom v2.8.3;
3. DoomRL Monsters Beta 7.3 or Colourful Hell v0.98c or Rampancy v1.3 or Dehacked Attack v3.1;
4. DoomRL Arsenal Extended 0.9be;
5. Corruption Cards 4.0;
6. DoomRPG;
7. DoomRPG compatibility patches (as per modifications).

**Comment by Forevener** [comment]
So basically it's 'Always last'

**Comment by WNC12k** [comment]
Yes

**Comment by WNC12k** [comment]
![Screenshot_20220905-163703_Discord](https://user-images.githubusercontent.com/40601544/188440125-805ec7bf-5cdd-4e77-a042-2021e07a50f9.jpg)

**Comment by WNC12k** [comment]
by the way, I still had a small bug. when I stretched the boot order window, all the contents disappeared. and appeared again after clicking the Reload button

**Comment by Forevener** [comment]
That's right, I've moved the switch for DoomRPG to the "Mods" tab, it feels more logical since DoomRPG is a mod.
As for patches - they shouldn't have been there in the first place - at least if they used version after 1.0.3 where patches were applied automatically and were not stored in the config.
Updates were working fine for a long time according to my data. Actually, I've used only the launcher to download and play your fork. So more information is needed.

Please send me the server's address (or invite), it seems my presence will be required there.

**Comment by Forevener** [comment]
> by the way, I still had a small bug. when I stretched the boot order window, all the contents disappeared. and appeared again after clicking the Reload button

This is really unusual. Can you try to replicate and tell me the algorithm to repeat that, please?

**Comment by WNC12k** [comment]
> Please send me the server's address (or invite), it seems my presence will be required there.

https://discord.com/invite/Whts7Bj

KYLE873 -> drpg

**Comment by WNC12k** [comment]
> This is really unusual. Can you try to replicate and tell me the algorithm to repeat that, please?

I'm trying, and I can't seem to cause it on purpose. I'll let you know if I find out why it happens.

**Comment by Forevener** [comment]
The new version is out, please take a look.
